
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CADENA FOR ID LLAVE_ABIERTA LLAVE_CERRADA N NUMERO OPERADOR OUT PABIERTO PCERRADO PRINTLN PUBLIC SIMBOLO STATIC SYSTEM VOIDprogram : PUBLIC STATIC VOID ID PABIERTO PCERRADO LLAVE_ABIERTA statements LLAVE_CERRADAstatements : statement statements\n                  | statement\n                  | emptystatement : N OPERADOR SIMBOLO\n                 | FOR PABIERTO statement PCERRADO LLAVE_ABIERTA statements LLAVE_CERRADA\n                 | LLAVE_ABIERTA statements LLAVE_CERRADAempty : '
    
_lr_action_items = {'PUBLIC':([0,],[2,]),'$end':([1,16,],[0,-1,]),'STATIC':([2,],[3,]),'VOID':([3,],[4,]),'ID':([4,],[5,]),'PABIERTO':([5,14,],[6,19,]),'PCERRADO':([6,20,21,22,26,],[7,-7,-5,23,-6,]),'LLAVE_ABIERTA':([7,8,9,11,19,20,21,23,24,26,],[8,9,9,9,9,-7,-5,24,9,-6,]),'N':([8,9,11,19,20,21,24,26,],[13,13,13,13,-7,-5,13,-6,]),'FOR':([8,9,11,19,20,21,24,26,],[14,14,14,14,-7,-5,14,-6,]),'LLAVE_CERRADA':([8,9,10,11,12,15,17,20,21,24,25,26,],[-8,-8,16,-3,-4,20,-2,-7,-5,-8,26,-6,]),'OPERADOR':([13,],[18,]),'SIMBOLO':([18,],[21,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statements':([8,9,11,24,],[10,15,17,25,]),'statement':([8,9,11,19,24,],[11,11,11,22,11,]),'empty':([8,9,11,24,],[12,12,12,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> PUBLIC STATIC VOID ID PABIERTO PCERRADO LLAVE_ABIERTA statements LLAVE_CERRADA','program',9,'p_program','analizador_lexico.py',83),
  ('statements -> statement statements','statements',2,'p_statements','analizador_lexico.py',87),
  ('statements -> statement','statements',1,'p_statements','analizador_lexico.py',88),
  ('statements -> empty','statements',1,'p_statements','analizador_lexico.py',89),
  ('statement -> N OPERADOR SIMBOLO','statement',3,'p_statement','analizador_lexico.py',93),
  ('statement -> FOR PABIERTO statement PCERRADO LLAVE_ABIERTA statements LLAVE_CERRADA','statement',7,'p_statement','analizador_lexico.py',94),
  ('statement -> LLAVE_ABIERTA statements LLAVE_CERRADA','statement',3,'p_statement','analizador_lexico.py',95),
  ('empty -> <empty>','empty',0,'p_empty','analizador_lexico.py',104),
]
